version:  '3'

services:

  ngrok:
    image: wernight/ngrok
    container_name: "${PROJECT_NAME}_ngrok"
    dns: dns
    depends_on:
      - reverse_proxy
    environment:
      - "NGROK_AUTH=${NGROK_AUTHTOKEN}"
    labels:
      - "traefik.docker.network=traefik_public"
      #Web Interface
      - "traefik.http.services.${PROJECT_NAME}_ngrok.loadbalancer.server.port=4040" # web interface port
      - "traefik.http.routers.${PROJECT_NAME}_ngrok.rule=Host(`ngrok.${PROJECT_BASE_URL}`)" # web interface url
      - "traefik.http.routers.${PROJECT_NAME}_ngrokh.entrypoints=web"
    networks:
      - traefik_public

networks:
  traefik_public:
    name: traefik_public
    driver: bridge