version: '3'

services:
 
  php:
    image: abgeo/php-symfony:${PHP_VERSION}
    container_name: "${PROJECT_NAME}_php"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_DRIVER: ${DB_DRIVER}
      COLUMNS: 80 # Set 80 columns for docker exec -it.
  #  volumes:
  #    - ./${PROJECT_DIR}:/var/www/html # Use bind mount
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_php.rule=Host(`${PROJECT_BASE_URL}`)"
