version:  '3'

services:

  
  ngrok: 
    image: wernight/ngrok
    container_name: "${PROJECT_NAME}-ngrok"
    depends_on:
      - reverse_proxy
    labels:
      - "traefik.docker.network=traefik-public"
      #Web Interface
      - "traefik.http.services.${PROJECT_NAME}-ngrok.loadbalancer.server.port=4040" # web interface port
      - "traefik.http.routers.${PROJECT_NAME}-ngrok.rule=Host(`ngrok.${PROJECT_BASE_URL}`)" # web interface url
      - "traefik.http.routers.${PROJECT_NAME}-ngrok.entrypoints=web"
    networks:
      - traefik-public
    command: sh -c "ngrok authtoken ${NGROK_AUTHTOKEN} && ngrok http ${DOMAIN}:80"

networks:
  traefik-public:
    name: traefik-public
    driver: bridge